# Generated by Django 5.2.8 on 2026-04-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id_juego', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.JSONField()),
            ],
            options={
                'db_table': 'pistas',
                'managed': False,
            },
        ),
    ]
